title: "Hugo Community Modules"
baseURL: "https://hugo-mods.github.io"
languageCode: "en-US"
theme: "github.com/kdevo/osprey-delight"
tags: ["hugo", "modules", "hugo-mods"]
#canonifyURLS: true
#googleAnalytics: ""
disableKinds: ["taxonomy", "taxonomyTerm"]
enableEmoji: true
pygmentsUseClasses: true

module:
  imports:
  - path: github.com/kdevo/osprey-delight 

## Generic theme parameters:
Params:
  author: "kdevo"
  description: "hugo-mods: Powerful community modules for Hugo, a static site generator."

  # logoBig appears at the top of the page. Use a path relative to the assets dir for auto-resizing. 
  logoBig: "logo.png"

  # logoSmall is the logo that will be shown in the left corner of the nav bar.
  #   Use a path relative to the assets dir for auto-resizing.
  logoSmall: "logo.png"

  # background can optionally be specified as an image layer behind logoBig at the top of the page (parallax effect).
  background: "background.jpg"

  # tagline (followed by a cursor) is shown at the top, below the logo
  #tagline: "Welcome!"
  # mdTagline can be used instead to specify the tagline in Markdown for more customizability.
  # Note that {cursor} is a placeholder and will be replaced by the actual cursor HTML when rendering.
  mdTagline: "## hugo mod get -u{cursor}"
  theme: "hugo-mods"
  favicon: "logo.png"

  opengraphImage: "background.jpg"

  # enforceSinglePage will enforce redirection to the baseURL for all sub-directories/-pages.
  #   Example: If you create about.md, Hugo will also create a '/about/index.html' which might not be what you want for a *single* page site. 
  #   If this switch is enabled, all these "orphan" files will contain only a redirect directive.
  enforceSinglePage: false

  # copyright flag generates a copyright notice in footer of your site.
  copyright: true

## Social links in footer:
  Social:
  - type: github
    url: "https://github.com/hugo-mods/"
  - type: heart
    url: "https://github.com/sponsors/kdevo"

## Theme features:
  Feat:
    # ajaxBasin requires Basin setup for a free contact form (see instructions in README).
    ajaxBasin: "https://usebasin.com/f/bc2e65d1edb1"

    # useStructuredData for your own https://schema.org/Person (SEO-friendly).
    #   This will be auto-generated dependent on the information you provide in this configuration.
    useStructuredData: true

    # structuredDataGitHubUser will tell the theme to use your USERNAME for querying the GitHub API to fetch more information about you for structured data.
    #   This will use information that is publically available about your GitHub user profile at https://api.github.com/users/{USERNAME}.
    structuredDataGitHubUser: "hugo-mods"

    # useTermynal enables Termynal (https://github.com/ines/termynal), a small JS library for showing a terminal "animation" from within your gallery item.
    #   The library has been stripped-down to a minimum to only have the necessary functionality.
    useTermynal: true

    googleTagManager: ""
  
  # Image resizing can be configured here (see README for more info):
  Image:
    Logo:
      resize: "600x"

    Gallery:
      resize: "600x"

    Background:
      resize: "1920x"
      resizeLQIP: "256x"
  
  lazyimg:
    resizer: auto
    renderer: lqip-webp

    # Resizer options:
    lqipSize: "120x Gaussian"
    maxSize: "1920x"
    responsiveSizes: ["320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x"]
    resizeOptions: "Lanczos q95"

    # Renderer options:
    #class: ""
    #alt: ""
    noscript: true
  
      

## Menu items are automatically added to navbar. Use content files for more advanced usage.
##   See: https://gohugo.io/content-management/menus/#add-content-to-menus
Menu:
  Main:

    - # name represents what's shown to the user in the nav bar. 
      name: "About"
      # identifier controls the section type (and therewith the appearence).
      identifier: about 
      # url must be an anchor, for smooth scrolling to it when clicking on the menu item.
      url: "/#about"
      # weight controls the order of the menu items.
      weight: 1
    - name: "Mods"
      identifier: gallery
      url: "/#mods"
      weight: 2
    - name: "Blog"
      identifier: blog
      url: "/#blog"
      weight: 3
    - name: "Join"
      identifier: contact
      url: "/#join"
      weight: 4
    # - name: ""
    #   # pre makes it possible to use arbitrary HTML before the name, e.g. referencing icons here is possible:
    #   pre: '<svg class="icon"><use xlink:href="#icon-external"/></svg>&nbsp;'
    #   url: "https://kdevo.github.io/"
    #   weight: 5
